[font]
size = 13.0

[font.normal]
#family = 'Hack'
family = 'Jetbrains Mono Light'
style = 'Regular'

[shell]
args = ['--login']
program = '/bin/fish'

[window]
dynamic_padding = true

# Colors (Gruvbox dark)
[colors]
  # Default colors
[colors.primary]
# hard contrast = background = '0x1d2021'
    background = '0x33312F'
# soft contrast = background = '0x32302f'
    foreground = '0xebdbb2'



  # Normal colors
[colors.normal]
    white   = '0xa89984'
    red     = '0xcc241d'
    green   = '0x98971a'
    yellow  = '0xd79921'
    blue    = '0x458588'
    magenta = '0xb16286'
    cyan    = '0x689d6a'
    black    = '0xa89984'

  # Bright colors
[colors.bright]
    white   = '0xebdbb2'
    red     = '0xfb4934'
    green   = '0xb8bb26'
    yellow  = '0xfabd2f'
    blue    = '0x83a598'
    magenta = '0xd3869b'
    cyan    = '0x8ec07c'
    black    = '0x928374'
